### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [JaredCorduan/JaredCorduan.github.io#1]
Hi! I am the editor of Haskell Weekly. I would like to be notified when you publish a new post, but as far as I can tell your site does not have a feed. Would you mind adding an Atom or RSS feed? Hakyll supports this out of the box: https://jaspervdj.be/hakyll/tutorials/05-snapshots-feeds.html. Thanks!

**Comment by JaredCorduan** [comment]
thank you! I'd be happy to add a feed! I will let you know when I've added it.

**Comment by JaredCorduan** [comment]
I added a [feed](https://jaredcorduan.github.io/rss.xml) @tfausak, thanks for the suggestion!

**Comment by tfausak** [comment]
Perfect, thanks!
