### ISSUE TITLE
Google Fonts HTTPS

### ISSUE THREAD

**Issue by genos** [JaredCorduan/JaredCorduan.github.io#3]
I'm currently enjoying reading your post on the Rubik's Cube Group, but my browser was unable to load the [Open Sans](https://fonts.google.com/specimen/Open+Sans) font from Google because it's imported in the CSS from `http://fonts.google.com` rather than `https://fonts.google.com`. I think it's probably a one character addition to fix this, but I'm no CSS master.

Thanks again for the interesting reading!

**Comment by genos** [comment]
Specifically, if you change the `http` to `https` at the start of [`default.css`](https://github.com/JaredCorduan/JaredCorduan.github.io/blob/master/css/default.css), I think it'd fix my browser's complaint.

**Comment by JaredCorduan** [comment]
Thank you for letting me know @genos ! I've switched it to https, let me know if this solves the problem.

**Comment by genos** [comment]
Looks great. Thanks for fixing my pedantic issue, and thanks again for the interesting post!

**Comment by JaredCorduan** [comment]
I'm glad that worked! Thank you for helping me make the blog better for everyone!
